steps:
        - id: go_version
          name: "gcr.io/cloud-builders/go"
          args: ["version"]

        - id: go_test
          name: "gcr.io/cloud-builders/go"
          args: ["test","-v",".././..."]

        - id: packer_build
          name: "gcr.io/gep-kne/packer"
          args: ["debian.pkr.hcl"]
