# This topology consists of two Nokia SR Linux IXR-6e nodes running 22.11.2 release and connected with a single link over ethernet-1/1 interfaces.
# Each of the nodes comes up with a startup config which is sourced from the config.cli file;
# the startup config contains a self-signed TLS cert and has gnmi, gnoi, gribi, p4rt services enabled
#
# Read more about this topology at http://learn.srlinux.dev/tutorials/infrastructure/kne/srl-with-oc-services/

name: "2-srl-ixr6"
nodes: {
    name: "srl1"
    vendor: NOKIA
    model: "ixr6e"
    config:{
        # when `image` is not specified under `config`, the "ghcr.io/nokia/srlinux:latest" container image is used by default
        # SR Linux can accept both complete config files in JSON format, or partial/full config snippets in the CLI format.
        # nodes are configured with a partial config snippet in CLI format that adds configuration relevant for this example lab.
        file: "config.cfg"
    }
    interfaces: {
        key: "e1-1"
        value: {
            name: "ethernet-1/1"
        }
    }
}

nodes: {
    name: "srl2"
    vendor: NOKIA
    model: "ixr6e"
    config:{
        # when `image` is not specified under `config`, the "ghcr.io/nokia/srlinux:latest" container image is used by default
        file: "config.cfg"
    }
    interfaces: {
        key: "e1-1"
        value: {
            name: "ethernet-1/1"
        }
    }
}

links: {
    a_node: "srl1"
    a_int: "e1-1"
    z_node: "srl2"
    z_int: "e1-1"
}

