name: "2srl-certs"
nodes: {
    name: "r1"
    vendor: NOKIA
    config: {
        # when `image` is not specified under `config`, the "ghcr.io/nokia/srlinux:latest" container image is used by default
        cert: {
            self_signed: {
                cert_name: "kne-profile",
                key_name: "N/A",
                key_size: 4096,
            }
        }
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services: {
        key: 57400
        value: {
            name: "gnmi"
            inside: 57400
        }
    }
}
nodes: {
    name: "r2"
    vendor: NOKIA
    config: {
        # when `image` is not specified under `config`, the "ghcr.io/nokia/srlinux:latest" container image is used by default
        cert: {
            self_signed: {
                cert_name: "kne-profile",
                key_name: "N/A",
                key_size: 4096,
            }
        }
    }
    services: {
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
}

links: {
    a_node: "r1"
    a_int: "e1-1"
    z_node: "r2"
    z_int: "e1-1"
}

