// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.31.1
// source: ciena.proto

package ciena

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemEquipment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Mount point for the files inside the pod.
	MountDir      string `protobuf:"bytes,1,opt,name=mount_dir,json=mountDir,proto3" json:"mount_dir,omitempty"`
	EquipmentJson string `protobuf:"bytes,2,opt,name=equipment_json,json=equipmentJson,proto3" json:"equipment_json,omitempty"`
}

func (x *SystemEquipment) Reset() {
	*x = SystemEquipment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ciena_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemEquipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEquipment) ProtoMessage() {}

func (x *SystemEquipment) ProtoReflect() protoreflect.Message {
	mi := &file_ciena_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEquipment.ProtoReflect.Descriptor instead.
func (*SystemEquipment) Descriptor() ([]byte, []int) {
	return file_ciena_proto_rawDescGZIP(), []int{0}
}

func (x *SystemEquipment) GetMountDir() string {
	if x != nil {
		return x.MountDir
	}
	return ""
}

func (x *SystemEquipment) GetEquipmentJson() string {
	if x != nil {
		return x.EquipmentJson
	}
	return ""
}

// Ciena specific vendor data for KNE
type CienaConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemEquipment *SystemEquipment `protobuf:"bytes,1,opt,name=system_equipment,json=systemEquipment,proto3" json:"system_equipment,omitempty"`
}

func (x *CienaConfig) Reset() {
	*x = CienaConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ciena_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CienaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CienaConfig) ProtoMessage() {}

func (x *CienaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ciena_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CienaConfig.ProtoReflect.Descriptor instead.
func (*CienaConfig) Descriptor() ([]byte, []int) {
	return file_ciena_proto_rawDescGZIP(), []int{1}
}

func (x *CienaConfig) GetSystemEquipment() *SystemEquipment {
	if x != nil {
		return x.SystemEquipment
	}
	return nil
}

var File_ciena_proto protoreflect.FileDescriptor

var file_ciena_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x69, 0x65, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x69, 0x65, 0x6e, 0x61, 0x22, 0x55, 0x0a, 0x0f, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x44, 0x69, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x50, 0x0a, 0x0b, 0x43,
	0x69, 0x65, 0x6e, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x41, 0x0a, 0x10, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x5f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x69, 0x65, 0x6e, 0x61, 0x2e, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0f, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x27, 0x5a,
	0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6b, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x69, 0x65, 0x6e, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ciena_proto_rawDescOnce sync.Once
	file_ciena_proto_rawDescData = file_ciena_proto_rawDesc
)

func file_ciena_proto_rawDescGZIP() []byte {
	file_ciena_proto_rawDescOnce.Do(func() {
		file_ciena_proto_rawDescData = protoimpl.X.CompressGZIP(file_ciena_proto_rawDescData)
	})
	return file_ciena_proto_rawDescData
}

var file_ciena_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ciena_proto_goTypes = []interface{}{
	(*SystemEquipment)(nil), // 0: ciena.SystemEquipment
	(*CienaConfig)(nil),     // 1: ciena.CienaConfig
}
var file_ciena_proto_depIdxs = []int32{
	0, // 0: ciena.CienaConfig.system_equipment:type_name -> ciena.SystemEquipment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ciena_proto_init() }
func file_ciena_proto_init() {
	if File_ciena_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ciena_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemEquipment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ciena_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CienaConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ciena_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ciena_proto_goTypes,
		DependencyIndexes: file_ciena_proto_depIdxs,
		MessageInfos:      file_ciena_proto_msgTypes,
	}.Build()
	File_ciena_proto = out.File
	file_ciena_proto_rawDesc = nil
	file_ciena_proto_goTypes = nil
	file_ciena_proto_depIdxs = nil
}
