duts {
  id: "ceos"
  vendor: ARISTA
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
  ports {
    id: "port5"
  }
  ports {
    id: "port6"
  }
}
duts {
  id: "cptx"
  vendor: JUNIPER
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
  ports {
    id: "port5"
  }
  ports {
    id: "port6"
  }
}
duts {
  id: "srl"
  vendor: NOKIA
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
  ports {
    id: "port5"
  }
  ports {
    id: "port6"
  }
}
duts {
  id: "xrd"
  vendor: CISCO
  hardware_model: "xrd"
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
  ports {
    id: "port5"
  }
  ports {
    id: "port6"
  }
}
duts {
  id: "e8000"
  vendor: CISCO
  hardware_model: "8201"
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
  ports {
    id: "port5"
  }
  ports {
    id: "port6"
  }
}
duts {
  id: "lemming"
  vendor: OPENCONFIG
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
  ports {
    id: "port5"
  }
  ports {
    id: "port6"
  }
}
ates {
  id: "otg"
  vendor: IXIA
  ports {
    id: "port1"
  }
  ports {
    id: "port2"
  }
  ports {
    id: "port3"
  }
  ports {
    id: "port4"
  }
  ports {
    id: "port5"
  }
  ports {
    id: "port6"
  }
}
links {
  a: "otg:port1"
  b: "ceos:port1"
}
links {
  a: "otg:port2"
  b: "cptx:port1"
}
links {
  a: "otg:port3"
  b: "srl:port1"
}
links {
  a: "otg:port4"
  b: "xrd:port1"
}
links {
  a: "otg:port5"
  b: "e8000:port1"
}
links {
  a: "otg:port6"
  b: "lemming:port1"
}
links {
  a: "ceos:port2"
  b: "cptx:port2"
}
links {
  a: "ceos:port3"
  b: "srl:port2"
}
links {
  a: "ceos:port4"
  b: "xrd:port2"
}
links {
  a: "ceos:port5"
  b: "e8000:port2"
}
links {
  a: "ceos:port6"
  b: "lemming:port2"
}
links {
  a: "cptx:port3"
  b: "srl:port3"
}
links {
  a: "cptx:port4"
  b: "xrd:port3"
}
links {
  a: "cptx:port5"
  b: "e8000:port3"
}
links {
  a: "cptx:port6"
  b: "lemming:port3"
}
links {
  a: "srl:port4"
  b: "xrd:port4"
}
links {
  a: "srl:port5"
  b: "e8000:port4"
}
links {
  a: "srl:port6"
  b: "lemming:port4"
}
links {
  a: "xrd:port5"
  b: "e8000:port5"
}
links {
  a: "xrd:port6"
  b: "lemming:port5"
}
links {
  a: "e8000:port6"
  b: "lemming:port6"
}

