name: "vendors"
nodes: {
  name: "ceos"
  vendor: ARISTA
  model: "ceos"
  os: "eos"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/arista/ceos:ga"
    config_path: "/mnt/flash"
    config_file: "startup-config"
    file: "ceos.cfg"
    cert: {
      self_signed: {
        cert_name: "gnmiCert.pem"
        key_name: "gnmiCertKey.pem"
        key_size: 4096
      }
    }
  }
}
nodes: {
  name: "cptx"
  vendor: JUNIPER
  model: "cptx"
  os: "evo"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/juniper/cptx:ga"
    config_path: "/home/evo/configdisk"
    config_file: "juniper.conf"
    file: "cptx.cfg"
    cert: {
      self_signed: {
        cert_name: "grpc-server-cert",
        key_name: "N/A",
        key_size: 4096,
      }
    }
  }
   services:{
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services:{
        key: 9337
        value: {
            name: "gnoi"
            inside: 32767
        }
    }
    services:{
        key: 9339
        value: {
            name: "gnmi"
            inside: 32767
        }
    }
    services:{
        key: 9340
        value: {
            name: "gribi"
            inside: 32767
        }
    }
    services:{
        key: 9559
        value: {
            name: "p4rt"
            inside: 32767
        }
    }
  interfaces: {
    key: "eth4"
    value: {
      name: "et-0/0/0"
    }
  }
  interfaces: {
    key: "eth5"
    value: {
      name: "et-0/0/1"
    }
  }
  interfaces: {
    key: "eth6"
    value: {
      name: "et-0/0/2"
    }
  }
  interfaces: {
    key: "eth7"
    value: {
      name: "et-0/0/3"
    }
  }
  interfaces: {
    key: "eth8"
    value: {
      name: "et-0/0/4"
    }
  }
  interfaces: {
    key: "eth9"
    value: {
      name: "et-0/0/5"
    }
  }
  interfaces: {
    key: "eth10"
    value: {
      name: "et-0/0/6"
    }
  }
  interfaces: {
    key: "eth11"
    value: {
      name: "et-0/0/7"
    }
  }
  interfaces: {
    key: "eth12"
    value: {
      name: "et-0/0/8"
    }
  }
  interfaces: {
    key: "eth13"
    value: {
      name: "et-0/0/9"
    }
  }
}
nodes: {
  name: "srl"
  vendor: NOKIA
  model: "ixr6e"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/nokia/srlinux:ga"
    file: "srl.cfg.json"
  }
  services:{
    key: 22
    value: {
      name: "ssh"
      inside: 22
    }
  }
  services:{
    key: 9337
    value: {
      name: "gnoi"
      inside: 57400
    }
  }
  services:{
    key: 9339
    value: {
      name: "gnmi"
      inside: 57400
    }
  }
  services:{
    key: 9340
    value: {
      name: "gribi"
      inside: 57401
    }
  }
  services:{
    key: 9559
    value: {
      name: "p4rt"
      inside: 9559
    }
  }
}
nodes: {
  name: "xrd"
  vendor: CISCO
  model: "xrd"
  os: "ios-xr"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/cisco/xrd:ga"
    file: "xrd.cfg"
  }
  services:{
    key: 22
    value: {
      name: "ssh"
      inside: 22
    }
  }
  services:{
    key: 9339
    value: {
      name: "gnmi"
      inside: 57400
    }
  }
  services:{
    key: 9340
    value: {
        name: "gribi"
        inside: 57400
      }
  }
  services:{
    key: 9337
    value: {
      name: "gnoi"
      inside: 57400
    }
  }
  services:{
    key: 9559
    value: {
      name: "p4rt"
      inside: 57400
    }
  }
}
nodes: {
  name: "otg"
  vendor: KEYSIGHT
  version: "0.0.1-9999"
  services: {
    key: 443
    value: {
      name: "https"
      inside: 443
    }
  }
  services: {
    key: 40051
    value: {
      name: "grpc"
      inside: 40051
    }
  }
  services: {
    key: 50051
    value: {
      name: "gnmi"
      inside: 50051
    }
  }
}
# ceos - xrd
links: {
  a_node: "ceos"
  a_int: "eth1"
  z_node: "xrd"
  z_int: "eth1"
}
links: {
  a_node: "ceos"
  a_int: "eth2"
  z_node: "xrd"
  z_int: "eth2"
}
links: {
  a_node: "ceos"
  a_int: "eth3"
  z_node: "xrd"
  z_int: "eth3"
}
# ceos - cptx
links: {
  a_node: "ceos"
  a_int: "eth4"
  z_node: "cptx"
  z_int: "eth4"
}
links: {
  a_node: "ceos"
  a_int: "eth5"
  z_node: "cptx"
  z_int: "eth5"
}
links: {
  a_node: "ceos"
  a_int: "eth6"
  z_node: "cptx"
  z_int: "eth6"
}
# xrd - cptx
links: {
  a_node: "xrd"
  a_int: "eth4"
  z_node: "cptx"
  z_int: "eth7"
}
links: {
  a_node: "xrd"
  a_int: "eth5"
  z_node: "cptx"
  z_int: "eth8"
}
links: {
  a_node: "xrd"
  a_int: "eth6"
  z_node: "cptx"
  z_int: "eth9"
}
# otg - everything
links: {
  a_node: "otg"
  a_int: "eth1"
  z_node: "ceos"
  z_int: "eth10"
}
links: {
  a_node: "otg"
  a_int: "eth2"
  z_node: "cptx"
  z_int: "eth10"
}
links: {
  a_node: "otg"
  a_int: "eth3"
  z_node: "srl"
  z_int: "eth10"
}
links: {
  a_node: "otg"
  a_int: "eth4"
  z_node: "xrd"
  z_int: "eth10"
}
# srl - ceos
links: {
  a_node: "srl"
  a_int: "eth1"
  z_node: "ceos"
  z_int: "eth7"
}
links: {
  a_node: "srl"
  a_int: "eth2"
  z_node: "ceos"
  z_int: "eth8"
}
links: {
  a_node: "srl"
  a_int: "eth3"
  z_node: "ceos"
  z_int: "eth9"
}
# srl - xrd
links: {
  a_node: "srl"
  a_int: "eth4"
  z_node: "xrd"
  z_int: "eth7"
}
links: {
  a_node: "srl"
  a_int: "eth5"
  z_node: "xrd"
  z_int: "eth8"
}
links: {
  a_node: "srl"
  a_int: "eth6"
  z_node: "xrd"
  z_int: "eth9"
}
# srl - cptx
links: {
  a_node: "srl"
  a_int: "eth7"
  z_node: "cptx"
  z_int: "eth11"
}
links: {
  a_node: "srl"
  a_int: "eth8"
  z_node: "cptx"
  z_int: "eth12"
}
links: {
  a_node: "srl"
  a_int: "eth9"
  z_node: "cptx"
  z_int: "eth13"
}
