name: "vendors"
nodes: {
  name: "ceos"
  vendor: ARISTA
  model: "ceos"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/arista/ceos:ga"
    file: "ceos.cfg"
  }
}
nodes: {
  name: "ncptx"
  vendor: JUNIPER
  model: "ncptx"
  # Disables the legacy gRPC server config that configures hot reloading
  # and PKI support. These are now configured by default in D47 and onwards.
  labels: {
    key: "legacy_grpc_server_config"
    value: "disabled"
  }
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/juniper/ncptx:ga"
    file: "juniper.cfg"
  }
  interfaces: {
    key: "eth5"
    value: {
      name: "et-0/0/0:0"
    }
  }
  interfaces: {
    key: "eth13"
    value: {
      name: "et-0/0/1:0"
    }
  }
  interfaces: {
    key: "eth21"
    value: {
      name: "et-0/0/2:0"
    }
  }
  interfaces: {
    key: "eth29"
    value: {
      name: "et-0/0/3:0"
    }
  }
  interfaces: {
    key: "eth37"
    value: {
      name: "et-0/0/4:0"
    }
  }
  interfaces: {
    key: "eth41"
    value: {
      name: "et-0/0/6:0"
    }
  }
}
nodes: {
  name: "srl"
  vendor: NOKIA
  model: "ixr6e"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/nokia/srlinux:ga"
    file: "srl.cfg"
  }
  interfaces: {
    key: "e1-1"
    value: {
      name: "ethernet-1/1"
    }
  }
  interfaces: {
    key: "e1-2"
    value: {
      name: "ethernet-1/2"
    }
  }
  interfaces: {
    key: "e1-3"
    value: {
      name: "ethernet-1/3"
    }
  }
  interfaces: {
    key: "e1-4"
    value: {
      name: "ethernet-1/4"
    }
  }
  interfaces: {
    key: "e1-5"
    value: {
      name: "ethernet-1/5"
    }
  }
  interfaces: {
    key: "e1-6"
    value: {
      name: "ethernet-1/6"
    }
  }
}
nodes: {
  name: "xrd"
  vendor: CISCO
  model: "xrd"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/cisco/xrd:ga"
    file: "cisco_xrd.cfg"
  }
  interfaces: {
    key: "eth1"
    value: {
      name: "GigabitEthernet0/0/0/0"
    }
  }
  interfaces: {
    key: "eth2"
    value: {
      name: "GigabitEthernet0/0/0/1"
    }
  }
  interfaces: {
    key: "eth3"
    value: {
      name: "GigabitEthernet0/0/0/2"
    }
  }
  interfaces: {
    key: "eth4"
    value: {
      name: "GigabitEthernet0/0/0/3"
    }
  }
  interfaces: {
    key: "eth5"
    value: {
      name: "GigabitEthernet0/0/0/4"
    }
  }
  interfaces: {
    key: "eth6"
    value: {
      name: "GigabitEthernet0/0/0/5"
    }
  }
}
nodes: {
  name: "8000e"
  vendor: CISCO
  model: "8201"
  config: {
    image: "us-west1-docker.pkg.dev/gep-kne/cisco/8000e:ga"
    file: "cisco_8000e.cfg"
  }
  interfaces: {
    key: "eth1"
    value: {
      name: "FourHundredGigE0/0/0/0"
    }
  }
  interfaces: {
    key: "eth2"
    value: {
      name: "FourHundredGigE0/0/0/1"
    }
  }
  interfaces: {
    key: "eth3"
    value: {
      name: "FourHundredGigE0/0/0/2"
    }
  }
  interfaces: {
    key: "eth4"
    value: {
      name: "FourHundredGigE0/0/0/3"
    }
  }
  interfaces: {
    key: "eth5"
    value: {
      name: "FourHundredGigE0/0/0/4"
    }
  }
  interfaces: {
    key: "eth6"
    value: {
      name: "FourHundredGigE0/0/0/5"
    }
  }
}
nodes: {
  name: "lemming"
  vendor: OPENCONFIG
  model: "LEMMING"
}
nodes: {
  name: "otg"
  vendor: KEYSIGHT
  version: "0.0.1-9999"
}
# Links from otg
links: {
  a_node: "otg"
  a_int: "eth1"
  z_node: "ceos"
  z_int: "eth1"
}
links: {
  a_node: "otg"
  a_int: "eth2"
  z_node: "ncptx"
  z_int: "eth5"
}
links: {
  a_node: "otg"
  a_int: "eth3"
  z_node: "srl"
  z_int: "e1-1"
}
links: {
  a_node: "otg"
  a_int: "eth4"
  z_node: "xrd"
  z_int: "eth1"
}
links: {
  a_node: "otg"
  a_int: "eth5"
  z_node: "8000e"
  z_int: "eth1"
}
links: {
  a_node: "otg"
  a_int: "eth6"
  z_node: "lemming"
  z_int: "eth1"
}
# Links from ceos
links: {
  a_node: "ceos"
  a_int: "eth2"
  z_node: "ncptx"
  z_int: "eth13"
}
links: {
  a_node: "ceos"
  a_int: "eth3"
  z_node: "srl"
  z_int: "e1-2"
}
links: {
  a_node: "ceos"
  a_int: "eth4"
  z_node: "xrd"
  z_int: "eth2"
}
links: {
  a_node: "ceos"
  a_int: "eth5"
  z_node: "8000e"
  z_int: "eth2"
}
links: {
  a_node: "ceos"
  a_int: "eth6"
  z_node: "lemming"
  z_int: "eth2"
}
# Links from ncptx
links: {
  a_node: "ncptx"
  a_int: "eth21"
  z_node: "srl"
  z_int: "e1-3"
}
links: {
  a_node: "ncptx"
  a_int: "eth29"
  z_node: "xrd"
  z_int: "eth3"
}
links: {
  a_node: "ncptx"
  a_int: "eth37"
  z_node: "8000e"
  z_int: "eth3"
}
links: {
  a_node: "ncptx"
  a_int: "eth41"
  z_node: "lemming"
  z_int: "eth3"
}
# Links from srl
links: {
  a_node: "srl"
  a_int: "e1-4"
  z_node: "xrd"
  z_int: "eth4"
}
links: {
  a_node: "srl"
  a_int: "e1-5"
  z_node: "8000e"
  z_int: "eth4"
}
links: {
  a_node: "srl"
  a_int: "e1-6"
  z_node: "lemming"
  z_int: "eth4"
}
# Links from xrd
links: {
  a_node: "xrd"
  a_int: "eth5"
  z_node: "8000e"
  z_int: "eth5"
}
links: {
  a_node: "xrd"
  a_int: "eth6"
  z_node: "lemming"
  z_int: "eth5"
}
# Links from 8000e
links: {
  a_node: "8000e"
  a_int: "eth6"
  z_node: "lemming"
  z_int: "eth6"
}

