// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: forward.proto

package forward

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Forward specific config data for KNE
type ForwardConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wires []*Wire `protobuf:"bytes,1,rep,name=wires,proto3" json:"wires,omitempty"`
}

func (x *ForwardConfig) Reset() {
	*x = ForwardConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardConfig) ProtoMessage() {}

func (x *ForwardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardConfig.ProtoReflect.Descriptor instead.
func (*ForwardConfig) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardConfig) GetWires() []*Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

// Wire is a connection between two endpoints intended to forward
// data bidirectionally between them. One of the endpoints must be of type Interface.
type Wire struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The a endpoint serves as the client endpoint in the bidirectional stream.
	A *Endpoint `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	// The z endpoint serves as the server endpoint in the bidirectional stream.
	Z *Endpoint `protobuf:"bytes,2,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Wire) Reset() {
	*x = Wire{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wire) ProtoMessage() {}

func (x *Wire) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wire.ProtoReflect.Descriptor instead.
func (*Wire) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{1}
}

func (x *Wire) GetA() *Endpoint {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *Wire) GetZ() *Endpoint {
	if x != nil {
		return x.Z
	}
	return nil
}

type Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Endpoint:
	//
	//	*Endpoint_Interface
	//	*Endpoint_LocalNode
	//	*Endpoint_RemoteNode
	Endpoint isEndpoint_Endpoint `protobuf_oneof:"endpoint"`
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{2}
}

func (m *Endpoint) GetEndpoint() isEndpoint_Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

func (x *Endpoint) GetInterface() *Interface {
	if x, ok := x.GetEndpoint().(*Endpoint_Interface); ok {
		return x.Interface
	}
	return nil
}

func (x *Endpoint) GetLocalNode() *LocalNode {
	if x, ok := x.GetEndpoint().(*Endpoint_LocalNode); ok {
		return x.LocalNode
	}
	return nil
}

func (x *Endpoint) GetRemoteNode() *RemoteNode {
	if x, ok := x.GetEndpoint().(*Endpoint_RemoteNode); ok {
		return x.RemoteNode
	}
	return nil
}

type isEndpoint_Endpoint interface {
	isEndpoint_Endpoint()
}

type Endpoint_Interface struct {
	// Interface is a local interface (ex. eth0) on the node.
	Interface *Interface `protobuf:"bytes,1,opt,name=interface,proto3,oneof"`
}

type Endpoint_LocalNode struct {
	// LocalNode is a node in the same cluster.
	LocalNode *LocalNode `protobuf:"bytes,2,opt,name=local_node,json=localNode,proto3,oneof"`
}

type Endpoint_RemoteNode struct {
	// RemoteNode is a node in a different cluster.
	RemoteNode *RemoteNode `protobuf:"bytes,3,opt,name=remote_node,json=remoteNode,proto3,oneof"`
}

func (*Endpoint_Interface) isEndpoint_Endpoint() {}

func (*Endpoint_LocalNode) isEndpoint_Endpoint() {}

func (*Endpoint_RemoteNode) isEndpoint_Endpoint() {}

type Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // TODO: Add MTU and other configurable fields.
}

func (x *Interface) Reset() {
	*x = Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{3}
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LocalNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Interface string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
}

func (x *LocalNode) Reset() {
	*x = LocalNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocalNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalNode) ProtoMessage() {}

func (x *LocalNode) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalNode.ProtoReflect.Descriptor instead.
func (*LocalNode) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{4}
}

func (x *LocalNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LocalNode) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type RemoteNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr      string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Interface string `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
}

func (x *RemoteNode) Reset() {
	*x = RemoteNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forward_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteNode) ProtoMessage() {}

func (x *RemoteNode) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteNode.ProtoReflect.Descriptor instead.
func (*RemoteNode) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{5}
}

func (x *RemoteNode) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RemoteNode) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

var File_forward_proto protoreflect.FileDescriptor

var file_forward_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x22, 0x34, 0x0a, 0x0d, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x23, 0x0a, 0x05, 0x77, 0x69, 0x72,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x2e, 0x57, 0x69, 0x72, 0x65, 0x52, 0x05, 0x77, 0x69, 0x72, 0x65, 0x73, 0x22, 0x48,
	0x0a, 0x04, 0x57, 0x69, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x01, 0x61, 0x12, 0x1f, 0x0a, 0x01, 0x7a, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x01, 0x7a, 0x22, 0xb7, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x48, 0x00, 0x52, 0x09,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x64,
	0x65, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x36,
	0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x22, 0x1f, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x09, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x22, 0x3e, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6b, 0x6e, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forward_proto_rawDescOnce sync.Once
	file_forward_proto_rawDescData = file_forward_proto_rawDesc
)

func file_forward_proto_rawDescGZIP() []byte {
	file_forward_proto_rawDescOnce.Do(func() {
		file_forward_proto_rawDescData = protoimpl.X.CompressGZIP(file_forward_proto_rawDescData)
	})
	return file_forward_proto_rawDescData
}

var file_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_forward_proto_goTypes = []interface{}{
	(*ForwardConfig)(nil), // 0: forward.ForwardConfig
	(*Wire)(nil),          // 1: forward.Wire
	(*Endpoint)(nil),      // 2: forward.Endpoint
	(*Interface)(nil),     // 3: forward.Interface
	(*LocalNode)(nil),     // 4: forward.LocalNode
	(*RemoteNode)(nil),    // 5: forward.RemoteNode
}
var file_forward_proto_depIdxs = []int32{
	1, // 0: forward.ForwardConfig.wires:type_name -> forward.Wire
	2, // 1: forward.Wire.a:type_name -> forward.Endpoint
	2, // 2: forward.Wire.z:type_name -> forward.Endpoint
	3, // 3: forward.Endpoint.interface:type_name -> forward.Interface
	4, // 4: forward.Endpoint.local_node:type_name -> forward.LocalNode
	5, // 5: forward.Endpoint.remote_node:type_name -> forward.RemoteNode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_forward_proto_init() }
func file_forward_proto_init() {
	if File_forward_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forward_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forward_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wire); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forward_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forward_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forward_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocalNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forward_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_forward_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Endpoint_Interface)(nil),
		(*Endpoint_LocalNode)(nil),
		(*Endpoint_RemoteNode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forward_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forward_proto_goTypes,
		DependencyIndexes: file_forward_proto_depIdxs,
		MessageInfos:      file_forward_proto_msgTypes,
	}.Build()
	File_forward_proto = out.File
	file_forward_proto_rawDesc = nil
	file_forward_proto_goTypes = nil
	file_forward_proto_depIdxs = nil
}
