# this topology consists of two Nokia SR Linux IXR-D2 nodes running 22.6.1 release
# each of the nodes comes up with a startup config applied which is sourced from 22.6.1.cfg.json file
# the startup config already contains a self-signed TLS cert and has gnmi server enabled
# this allows users to deploy this topology and start using gnmi
name: "2srl-certs"
nodes: {
    name: "r1"
    type: NOKIA_SRL
    config:{
        # container image to use for this SR Linux pod
        # can be cheked with `show version` cli command
        image: "ghcr.io/nokia/srlinux:22.6.1"
        # file property sets the path to the startup config file that srlinux will boot with
        # the path is relative to the topology file
        # this config file already contains tls profiles and gnmi server enabled
        file: "22.6.1.cfg.json"
    }
    services:{
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
    services:{
        key: 57400
        value: {
            name: "gnmi"
            inside: 57400
        }
    }
}
nodes: {
    name: "r2"
    type: NOKIA_SRL
    config:{
        # container image to use for this SR Linux pod
        # can be cheked with `show version` cli command
        image: "ghcr.io/nokia/srlinux:22.6.1"
        # file property sets the path to the startup config file that srlinux will boot with
        # the path is relative to the topology file
        # this config file already contains tls profiles and gnmi server enabled
        file: "22.6.1.cfg.json"
    }
    services:{
        key: 22
        value: {
            name: "ssh"
            inside: 22
        }
    }
}

links: {
    a_node: "r1"
    a_int: "e1-1"
    z_node: "r2"
    z_int: "e1-1"
}

