version: "2"
linters:
  default: none
  enable:
    - gocritic
    - gosec
    - govet
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-blank: true
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - appendAssign
    revive:
      severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
      - linters:
          - revive
        text: 'var-naming: don''t use leading k'
      - linters:
          - staticcheck
        text: 'SA1019:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
