---
#########################
#########################
## Golang Linter rules ##
#########################
#########################

# configure golangci-lint
# see https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  timeout: 10m
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - linters:
      - revive
      text: "var-naming: don't use leading k"
    - linters:
      - staticcheck
      text: "SA1019:"
linters:
  disable-all: true
  enable:
    - gosec
    - unconvert
    - goimports
    - gofmt
    - gocritic
    - govet
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  gocritic:
    disabled-checks:
      - singleCaseSwitch
      - appendAssign
  revive:
    ignore-generated-header: true
    severity: warning
