version: "2"
linters:
  default: none
  enable:
    - gosec
    - unconvert
    - gocritic
    - govet
    - revive
    - staticcheck
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-blank: true
    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - appendAssign
    revive:
      rules:
        - name: generated-header
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - gosec
          - goconst
        path: _test\.go
      - linters:
          - revive
        text: "var-naming: don't use leading k"
      - linters:
          - staticcheck
        text: "SA1019:"
    paths:
      # Exclude heavy directories here to prevent Github Actions timeout
      - examples
      - api
      - topo/node/testdata
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
