// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/moby/moby/client (interfaces: NetworkAPIClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "github.com/moby/moby/client"
)

// MockNetworkAPIClient is a mock of NetworkAPIClient interface.
type MockNetworkAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkAPIClientMockRecorder
}

// MockNetworkAPIClientMockRecorder is the mock recorder for MockNetworkAPIClient.
type MockNetworkAPIClientMockRecorder struct {
	mock *MockNetworkAPIClient
}

// NewMockNetworkAPIClient creates a new mock instance.
func NewMockNetworkAPIClient(ctrl *gomock.Controller) *MockNetworkAPIClient {
	mock := &MockNetworkAPIClient{ctrl: ctrl}
	mock.recorder = &MockNetworkAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkAPIClient) EXPECT() *MockNetworkAPIClientMockRecorder {
	return m.recorder
}

// NetworkConnect mocks base method.
func (m *MockNetworkAPIClient) NetworkConnect(arg0 context.Context, arg1 string, arg2 client.NetworkConnectOptions) (client.NetworkConnectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkConnect", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.NetworkConnectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkConnect indicates an expected call of NetworkConnect.
func (mr *MockNetworkAPIClientMockRecorder) NetworkConnect(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkConnect", reflect.TypeOf((*MockNetworkAPIClient)(nil).NetworkConnect), arg0, arg1, arg2)
}

// NetworkCreate mocks base method.
func (m *MockNetworkAPIClient) NetworkCreate(arg0 context.Context, arg1 string, arg2 client.NetworkCreateOptions) (client.NetworkCreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkCreate", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.NetworkCreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkCreate indicates an expected call of NetworkCreate.
func (mr *MockNetworkAPIClientMockRecorder) NetworkCreate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkCreate", reflect.TypeOf((*MockNetworkAPIClient)(nil).NetworkCreate), arg0, arg1, arg2)
}

// NetworkDisconnect mocks base method.
func (m *MockNetworkAPIClient) NetworkDisconnect(arg0 context.Context, arg1 string, arg2 client.NetworkDisconnectOptions) (client.NetworkDisconnectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkDisconnect", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.NetworkDisconnectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkDisconnect indicates an expected call of NetworkDisconnect.
func (mr *MockNetworkAPIClientMockRecorder) NetworkDisconnect(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkDisconnect", reflect.TypeOf((*MockNetworkAPIClient)(nil).NetworkDisconnect), arg0, arg1, arg2)
}

// NetworkInspect mocks base method.
func (m *MockNetworkAPIClient) NetworkInspect(arg0 context.Context, arg1 string, arg2 client.NetworkInspectOptions) (client.NetworkInspectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkInspect", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.NetworkInspectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkInspect indicates an expected call of NetworkInspect.
func (mr *MockNetworkAPIClientMockRecorder) NetworkInspect(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkInspect", reflect.TypeOf((*MockNetworkAPIClient)(nil).NetworkInspect), arg0, arg1, arg2)
}

// NetworkList mocks base method.
func (m *MockNetworkAPIClient) NetworkList(arg0 context.Context, arg1 client.NetworkListOptions) (client.NetworkListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkList", arg0, arg1)
	ret0, _ := ret[0].(client.NetworkListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkList indicates an expected call of NetworkList.
func (mr *MockNetworkAPIClientMockRecorder) NetworkList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkList", reflect.TypeOf((*MockNetworkAPIClient)(nil).NetworkList), arg0, arg1)
}

// NetworkPrune mocks base method.
func (m *MockNetworkAPIClient) NetworkPrune(arg0 context.Context, arg1 client.NetworkPruneOptions) (client.NetworkPruneResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkPrune", arg0, arg1)
	ret0, _ := ret[0].(client.NetworkPruneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkPrune indicates an expected call of NetworkPrune.
func (mr *MockNetworkAPIClientMockRecorder) NetworkPrune(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkPrune", reflect.TypeOf((*MockNetworkAPIClient)(nil).NetworkPrune), arg0, arg1)
}

// NetworkRemove mocks base method.
func (m *MockNetworkAPIClient) NetworkRemove(arg0 context.Context, arg1 string, arg2 client.NetworkRemoveOptions) (client.NetworkRemoveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkRemove", arg0, arg1, arg2)
	ret0, _ := ret[0].(client.NetworkRemoveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkRemove indicates an expected call of NetworkRemove.
func (mr *MockNetworkAPIClientMockRecorder) NetworkRemove(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkRemove", reflect.TypeOf((*MockNetworkAPIClient)(nil).NetworkRemove), arg0, arg1, arg2)
}
